### ISSUE TITLE
Question: Automatically create API Token OR allow user:pass for API usage

### ISSUE THREAD

**Issue by mrmunch** [bitnami/bitnami-docker-jenkins#53]
After Jenkins startup, I'd like to do some automatic configurations using the Jenkins API.
Per default, I am not able to access the API using "user:pass" (403). But when I manually login to Jenkins and manually create a new API Token, I am able to access the api using "user:token".

I'd like to avoid these manual steps.

So I'd like to know *how* I can configure my helm chart (or whatever) to either
a) allow "user:pass" for API usage 
or
b) set a default API token (which I can user later on)
?

**Comment by jotamartos** [comment]
Hi @mrmunch ,

Due to security reasons, we cannot generate a default API token in our solutions. I'll forward the information to our team so they evaluate the addition of an additional parameter in the solution to generate a new API token and display it when launching the solution. 

In the meantime, you will need to generate a new API token manually, either by using the Web interface or by using any other script (please check the Jenkins documentation for more information)

Thanks
