### ISSUE TITLE
how pass --prefix parameter

### ISSUE THREAD

**Issue by lerit** [bitnami/bitnami-docker-jenkins#59]
Good day,
I want to pass --prefix to jenkins,is there any parameter that i can do so?
```
--prefix=$PREFIX:
Runs Jenkins to include the $PREFIX at the end of the URL. For example, set --prefix=/jenkins to make Jenkins accessible at http://myServer:8080/jenkins
```

**Comment by dani8art** [comment]
Hi @lerit, we currently don't support prefix in our catalog due to design reason, however, with Jenkins shouldn't be difficult to set it up. Please follow the workaround below.

- Update the script `run.sh`

```
#!/bin/bash

USER="jenkins"
START_COMMAND="java ${JAVA_OPTS} -jar /opt/bitnami/jenkins/jenkins.war ${JENKINS_ARGS}"

if [[ "$(id -u)" = "0" ]]; then
    exec gosu "$USER" bash -c "$START_COMMAND"
else
    exec bash -c "$START_COMMAND"
fi
```

Then you can use two approaches

- Extend the images and add the script

```
FROM bitnami/jenkins:2

COPY run.sh /run.sh
```

- Or override it using a volume

```diff
    volumes:
      - "jenkins_data:/bitnami/jenkins"
+      - ./run.sh:/run.sh
```
Finally, add your Jenkins parameters

```diff
+    environment:
+      - JENKINS_ARGS="--prefix=/jenkins"
```

**Comment by lerit** [comment]
@dani8art  thank you! it work for me :)

**Comment by mehmetalisarac** [comment]
Is this problem suported now ? I'm using the kubernetes but cannot set the prefix variable. its not working
