### ISSUE TITLE
No user exists for uid 1001 when setting git repository

### ISSUE THREAD

**Issue by juanmime** [bitnami/bitnami-docker-jenkins#60]
**Description**

When you try to create a new task/job if you try to set a SSH GIT repository, with or without credentials, the GIT plugin returns:
No user exists for uid 1001

**Steps to reproduce the issue:**

1. Create a new task
2. Go to source code origin settings.
3. Choose GIT
4. Set the ssh URL you usually execute with git clone.
5. Set the credetials

**Describe the results you received:**

The plugin shows this error on screen:
```
Failed to connect to repository : Command "git ls-remote -h -- ssh://myuser@myserver:myport/mypath HEAD" returned status code 128:
stdout:
stderr: No user exists for uid 1001
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Describe the results you expected:**

No error.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24302
 Built: Fri Mar 23 08:31:36 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server: Docker Engine - Community
 Engine:
  Version:      18.09.4
  API version:  1.39 (minimum version 1.12)
  Go version:   go1.10.8
  Git commit:   d14af54
  Built:        Wed Mar 27 18:41:10 2019
  OS/Arch:      linux/amd64
  Experimental: false
```

- Output of `docker info`:

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 184
Server Version: 18.09.4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.111-boot2docker
Operating System: Boot2Docker 18.09.4 (TCL 8.2.1)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.935GiB
Name: default
ID: ZNJS:BZZM:UDEI:HFYD:PHGZ:QUF6:2T4G:NFAY:ZCVX:QJMJ:TPEW:VJ3G
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.20.1, build 5d8c71b2
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
This problem not only rise in a standalone container running in docker, also on kubernetes with bitnami's helm chart that uses this docker image.

**Comment by joancafom** [comment]
Hi @juanmime,

Thanks for your issue. I am still investigating the issue, but it seems to me that it is a problem with the plugin itself. From within the container, you can perform the `git ls-remote -h -- ssh://myuser@myserver:myport/mypath HEAD` operation and do not receive an error. 

On the other hand, I have tried using HTTPS and it seems to work for me. Would that be a possible option for you?
Thanks!

**Comment by MiellyEllen** [comment]
I am experiencing this same issue. Was there any resolution?
I have a jenkins job that is unable to connect to my remote repository in Gerrit, it fails, and even reports an error when I configure the job.
`
Failed to connect to repository : Command "git ls-remote -h -- ssh://skyfirebuilder@juno:2222/SKYFIRE HEAD" returned status code 128:stdout:stderr: No user exists for uid 1001 fatal: Could not read from remote repository.Please make sure you have the correct access rights and the repository exists.f
`
and when i run the job

`Started by user user
Running as SYSTEM
Building in workspace /opt/bitnami/jenkins/jenkins_home/workspace/git-pull
No credentials specified
Cloning the remote Git repository
Cloning repository ssh://skyfirebuilder@juno:2222/SKYFIRE
 > git init /opt/bitnami/jenkins/jenkins_home/workspace/git-pull # timeout=10
Fetching upstream changes from ssh://skyfirebuilder@juno:2222/SKYFIRE
 > git --version # timeout=10
 > git fetch --tags --force --progress -- ssh://skyfirebuilder@juno:2222/SKYFIRE +refs/heads/*:refs/remotes/origin/* # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- ssh://skyfirebuilder@juno:2222/SKYFIRE +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: No user exists for uid 1001
fatal: Could not read from remote repository.`

But when I manually exec into the container, the git fetch runs successfully.

`git fetch --tags --force --progress -- ssh://skyfirebuilder@juno:2222/SKYFIRE +refs/heads/*:refs/remotes/origin/* # timeout=10`

I am using Gerrit for my repository which requires ssh.

**Comment by joancafom** [comment]
Hi @MiellyEllen ,

I was able to reproduce the issue but as it was working within the container I suspected it was a problem with the plugin itself. However, based on your evidence, it seems to be happening in other ones as well. I have been able to investigate in the matter but was unlucky to find any fully functional workaround. 

I will create an internal task in order to further investigate in the matter and be able to provide with a solution. I do not know `Gerrit`, but could you use HTTPs as an alternative (it seems to work).

Thanks!

**Comment by MiellyEllen** [comment]
Thanks for the quick reply @joancafom , I was able to do an HTTP with Gerrit workaround. 

1.  First i had to download the certificate from the corporate gerrit server (click lock icon in chrome browser) and save it as a configMap.
2. I had to actually create a jenkins credential with my username (mbowman) and Gerrit's HTTP generated password. I named the cred mbowman-gerrit. 
3. Then I had to create a pipeine project and would force GIT to use the the certificate BEFORE trying to fetch the branch, then add my mbowman-gerrit credential when fetching. I was unable to set the git config globally (for all other pipelines) because git does not give you permission to do that in the container.


sh 'git init'

sh git config http.sslCAInfo path-to-certificate

git branch: 'branchname', credentialsId:  'mbowman-gerrit' url: 'repository-url'

Lots of hoops, but it works

**Comment by joancafom** [comment]
Thank you so much for sharing your solution! We will take it into account when implementing the fix.

Best regards

**Comment by danielprado** [comment]
Any news on this? I've exactly the same problem with de git plugin and gitlab.

**Comment by andresbono** [comment]
Hi @danielprado, this issue has not been addressed yet. As a workaround, can you either try HTTPs instead of SSH or create a custom image like this one:

```Dockerfile
FROM bitnami/jenkins:2-debian-10
USER root
RUN echo "jenkins:x:$(id -g):" >> /etc/groups
RUN echo "jenkins:x:1001:$(id -g):Jenkins:$JENKINS_HOME:/bin/false" >> /etc/passwd
USER 1001
```

We haven't tested it in depth, but it may work as a temporary solution.

**Comment by ianibo** [comment]
Also encountering this via the helm chart install - any workaround when it's not possible to use https? ty

**Comment by andresbono** [comment]
Hi @ianibo, did you try the custom image commented in https://github.com/bitnami/bitnami-docker-jenkins/issues/60#issuecomment-708305057?

**Comment by kreeuwijk** [comment]
I was able to fix this in Kubernetes by setting runAsUser to a valid userID that existed in the argo-cd-repo-server container:
```
       securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
```

**Comment by rafariossaa** [comment]
Hi,
  Thanks for coming back and sharing your workaround.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
