### ISSUE TITLE
Install arcanist for Phabricator

### ISSUE THREAD

**Issue by MattCrum1** [bitnami/bitnami-docker-jenkins#63]
I'm trying to link Jenkins with Phabricator (using your Phabricator docker image), which requires that the command line tool Arcanist is installed in the Jenkins container - according to these instructions:

https://github.com/uber/phabricator-jenkins-plugin

When I connect to the container using `docker exec -it jenkins bash`, it logs me in as "jenkins" with no access to install packages using apt.

Can you please advise how I can install Arcanist?

**Comment by FraPazGal** [comment]
Hi @MattCrum1!

As this is a non-root container, you won't be able to access shell as root. An easy way would be to customize our image so that it installs `Arcanist`. Although it isn't from this container, you can look into the [Customize this image](https://github.com/bitnami/bitnami-docker-mariadb#extend-this-image) section of our `mariadb` container. In your case, an approximate example of such customization would be:

```Dockerfile
FROM bitnami/phabricator
LABEL maintainer "Bitnami <containers@bitnami.com>"

## Install 'arcanist'
USER 0
RUN install_packages arcanist
USER 1001
```

**Comment by FraPazGal** [comment]
Hi @MattCrum1,

Did the solution provided work for you? If not, please feel free to reach out.

**Comment by MattCrum1** [comment]
Hi @FraPazGal - 

Apologies for the slow response; I've not had time to give this a go but am comfortable that it will work when I try it. It might be worth installing Arcanist in your Jenkins image, or adding a capability to install optional packages? I imagine there are a few teams who would want to link your Jenkins and Phabricator containers together?

I'll close this for now - thanks.
