### ISSUE TITLE
How does the jenkins deployed by kubernetes use docker effectively?

### ISSUE THREAD

**Issue by 1998729** [bitnami/bitnami-docker-jenkins#74]
hi I am currently using bitnami's image to deploy in k8s, but I found that many binary services in it are not pre-installed. For example, I want to use docker in this container jenkins. How should I install it effectively?

**Comment by 1998729** [comment]
Or after using k8s to deploy jenkins, basically every build is deployed with jenkins-slave, and it cannot be deployed through jenkins in the container.?

**Comment by 1998729** [comment]
![image](https://user-images.githubusercontent.com/88186802/144351797-30c01f95-48a9-46e1-b586-75eeaede14fb.png)

**Comment by carrodher** [comment]
Please note the Jenkins container is non-root by default, the issue you're facing is because the non-root user running in the container is not able to execute Docker. You will need to change the user.

In the following links you can find more info about this topic:
- https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/
- https://docs.bitnami.com/tutorials/work-with-non-root-containers/
- https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html
- https://engineering.bitnami.com/articles/running-non-root-containers-on-openshift.html
